### PR TITLE
Veprbl and mvorl patches

### PR DESCRIPTION
**Pull request by RaymiiOrg**
Added the following:

From @veprbl: 

- https://github.com/veprbl/es40/commit/3f2e410c50670a8edcc5edc6b7da8842ec0f80d5 (skip srm memtest 1)
- https://github.com/veprbl/es40/commit/8bf4c91d40ff07b73939340b8d4a320c9fce6084#diff-c2e85483170eecdd55efe0ce7e3d09aab6d8112dc6630531f6ee14762687333f (skip srm memtest 2)
- https://github.com/veprbl/es40/commit/ac7e9a8b1e6df65121aa1944021af8d81aaad83f (netbsd boot)

From @mvorl:

- https://github.com/mvorl/es40/commit/980050d2d5db9210b00f4a4084e3cc219f839fe4 ( Replaced ! by ~ )
- https://github.com/mvorl/es40/commit/9ec73eb50e3261075cba33bbb583476ef1141f89 (  Replaced ! by ~  )

One change of my own, in the network code, throw a std::runtime instead of the macro. This branch started as my network troubleshooting branch, then I found the skip memtest patch, then I thought, lets take all the interesting patches. It still had the network debug in there, which I removed, but left the throw.

### CODE REVIEW

**Comment by lenticularis39** [comment]
Nice! I'll look into the patches and fix the code style where needed. 

Maybe the NetBSD clock patch also helps with Linux, which also hangs at boot similarly to NetBSD. Anyway if NetBSD boots it could be used in tests :) (I don't quite understand how MC146818 is related to the ALi card, but that's another matter.)

As of the memory test skipping - considering it's a hack based on an absolute memory address (and therefore likely working only with one specific version of the firmware) I don't think it's a good idea to enable it by default - I'll add a configuration option for that.

I've already fixed some `!` -> `~` bugs, but seems like I didn't notice all of them :D 

I have one question to the replacement of the `FAILURE` macros in the Ethernet controller with `std::runtime_error` - what is the purpose of this change? The `FAILURE` macros (which actually throw a POCO exception - this may be changed if POCO is replaced with Qt Core in the future) are used at all other places in the code if I'm not mistaken, and I believe this should be kept consistent unless there's a specific reason why not.

**Comment by RaymiiOrg** [comment]
I've removed the `throw std::runtime_error`. I do agree that it should be consistent with the rest of the code. I was using this branch to debug networking at first, that is when I changed it, should have reverted it back. 

What do the `!` vs `~` changes do / fix?

A configuration option for the memtest skip is quite a good idea. I've now set axpbox to have 1024MB RAM, and when debugging and rebooting, skipping that test saves quite a bit of time. 

Do note that I'm not very much in the actual emulation codebase yet. You might have noticed all my patches are either build system or other people's work, no significant changes yet. But, as more (simple) bugs turn up I might be able to help some more.

**Comment by lenticularis39** [comment]
> What do the `!` vs `~` changes do / fix?

`~` (bitwise negation) is used together with `&` (bitwise and) to "turn off" a bit in a register, however `!` (logical negation) turns a 0 into a 1 and everything else into a `0` (the whole number, not bitwise), effectively making the operation do nothing.

> A configuration option for the memtest skip is quite a good idea. I've now set axpbox to have 1024MB RAM, and when debugging and rebooting, skipping that test saves quite a bit of time.

Also on slower devices it takes long even for 256 MB.

> Do note that I'm not very much in the actual emulation codebase yet. You might have noticed all my patches are either build system or other people's work, no significant changes yet. But, as more (simple) bugs turn up I might be able to help some more.

That's understandable - I'm glad someone is helping me out with the project, since my time is obviously limited by my work and school.

**Comment by lenticularis39** [comment]
I rebased the branch, excluded the "Re-enable nonblocking pcap" commit (that doesn't seem to do anything about the network) and the two commits about the `std::runtime_error` that cancel each other.

I also refactored the commit adding MC146818 periodic interrupt support (it's done in a hacky way using a static variable inside a standalone block - I moved the code into a function and the static variable into the ALi's state). Currently I'm installing NetBSD 6.1.2 (it booted fine) - I hope it'll install successfully.

After that's done I'll merge the PR including my changes, if you don't plan to push some more commits.

**Comment by lenticularis39** [comment]
So NetBSD 6.1.2 installs and boots seamlessly; 9.0 crashes the emulator because of unknown SCSI instruction.

obrazek

**Comment by RaymiiOrg** [comment]
I wasn't planning more commits in this branch. Cool that netbsd runs 😁. Does 9 boot with an ide disk?

**Comment by lenticularis39** [comment]
> I wasn't planning more commits in this branch. 

OK, I'll merge it.

> Cool that netbsd runs grin. Does 9 boot with an ide disk?

It does - now trying to install it. I'll update the [Guest support](https://github.com/lenticularis39/axpbox/wiki/Guest-support) wiki page once I know the result (and I'll also revisit the other operating systems - the lack of periodic interrupt support could have cause much more problems that NetBSD not booting).

**Comment by lenticularis39** [comment]
obrazek

**Comment by krytarowski** [comment]
CC: @thorpej

**Pull request closed without merging**
